@extends('layouts.app')
@section('content')
<div class="mx-auto max-w-2xl"><h1 class="mb-2 text-3xl font-bold">Ambil Bukti Piket</h1><p class="mb-5 text-slate-600">Izinkan kamera dan GPS. Lokasi akan diperbarui tepat sebelum dikirim.</p><video id="camera" autoplay playsinline class="w-full rounded-xl bg-black"></video><canvas id="canvas" class="hidden"></canvas><img id="preview" class="mt-4 hidden w-full rounded-xl" alt="Pratinjau bukti"><form id="upload-form" method="POST" action="{{ route('piket.upload') }}" class="mt-4 space-y-3">@csrf<input type="hidden" name="photo" id="photo"><input type="hidden" name="latitude" id="latitude"><input type="hidden" name="longitude" id="longitude"><input type="hidden" name="accuracy" id="accuracy"><div class="flex gap-3"><button type="button" id="capture" class="rounded bg-indigo-700 px-4 py-2 text-white">Ambil Foto</button><button type="submit" id="submit" disabled class="rounded bg-emerald-700 px-4 py-2 text-white disabled:opacity-40">Kirim Bukti</button></div><p id="status" class="text-sm text-slate-600" aria-live="polite"></p></form></div>
<script>
const video=document.querySelector('#camera'),canvas=document.querySelector('#canvas'),photo=document.querySelector('#photo'),preview=document.querySelector('#preview'),capture=document.querySelector('#capture'),submit=document.querySelector('#submit'),status=document.querySelector('#status');
let cameraStream;
navigator.mediaDevices?.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false}).then(stream=>{cameraStream=stream;video.srcObject=stream}).catch(()=>status.textContent='Kamera tidak dapat diakses. Pastikan izin kamera aktif dan halaman menggunakan HTTPS.');
capture.addEventListener('click',()=>{if(!video.videoWidth){status.textContent='Kamera belum siap. Tunggu sebentar lalu coba lagi.';return}const scale=Math.min(1,1600/video.videoWidth);canvas.width=Math.round(video.videoWidth*scale);canvas.height=Math.round(video.videoHeight*scale);canvas.getContext('2d').drawImage(video,0,0,canvas.width,canvas.height);photo.value=canvas.toDataURL('image/jpeg',.72);preview.src=photo.value;preview.classList.remove('hidden');submit.disabled=false;status.textContent='Foto siap. Tekan Kirim Bukti untuk mengambil GPS terbaru.'});
document.querySelector('#upload-form').addEventListener('submit',e=>{if(!photo.value){e.preventDefault();return}e.preventDefault();if(!navigator.geolocation){status.textContent='Browser ini tidak mendukung GPS.';return}submit.disabled=true;capture.disabled=true;status.textContent='Mengambil lokasi GPS terbaru...';navigator.geolocation.getCurrentPosition(pos=>{document.querySelector('#latitude').value=pos.coords.latitude;document.querySelector('#longitude').value=pos.coords.longitude;document.querySelector('#accuracy').value=pos.coords.accuracy;status.textContent='GPS ditemukan. Mengirim foto, jangan tutup halaman...';cameraStream?.getTracks().forEach(track=>track.stop());HTMLFormElement.prototype.submit.call(e.target)},error=>{submit.disabled=false;capture.disabled=false;status.textContent=error.code===3?'GPS terlalu lama merespons. Pindah ke area terbuka lalu coba lagi.':'GPS tidak dapat diakses. Aktifkan lokasi dan izinkan akses.'},{enableHighAccuracy:true,timeout:15000,maximumAge:0})});
</script>@endsection
