name: Deploy Laravel Project

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /www/wwwroot/si-piket.kezadev.my.id
            
            git pull origin main
            
            composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev
            
            php artisan migrate --force
            
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            
            chown -R www:www /www/wwwroot/si-piket.kezadev.my.id
            chmod -R 775 /www/wwwroot/si-piket.kezadev.my.id/storage /www/wwwroot/si-piket.kezadev.my.id/bootstrap/cache